### ISSUE TITLE
Párrafos separados

### ISSUE THREAD

**Issue by laurasandoval** [bicubico/nc_epub#3]
Hola! Encontré un par de párrafos que parece se separaron (quizás sea error de la app de libros de iOS)

![image](https://user-images.githubusercontent.com/45631530/177351269-a6f8c322-f22e-400e-bb03-2ae126bdee53.jpeg)

![image](https://user-images.githubusercontent.com/45631530/177351302-5fea02d0-0e52-4c40-96c4-1273fd333a33.jpeg)

**Comment by asophila** [comment]
Corregido. Muchas gracias!!!
