### ISSUE TITLE
Opening and ending tag mismatch: body line 10 and p

### ISSUE THREAD

**Issue by willps** [bicubico/nc_epub#4]
Apple Books app en iOS. 

![image](https://user-images.githubusercontent.com/7906801/177416735-97e27ff0-d5e0-4423-9d9a-b4c895517981.png)

**Comment by asophila** [comment]
Resuelto. Error de mezcla de estilos

**Comment by asophila** [comment]
Gracias!

**Comment by willps** [comment]
Gracias a ti. Excelente trabajo.
